inherit_from:
  - .rubocop_todo.yml
  - https://raw.githubusercontent.com/moneyadviceservice/mas-standards/master/.rubocop.yml

Metrics/LineLength:
  Max: 120
AllCops:
  Exclude:
  - 'app/helpers/application_helper.rb'
  - 'bin/**/*'
  - 'config/**/*'
  - 'db/**/*'
  - 'Guardfile'
  - 'lib/tasks/**/*'
  - 'node_modules/**/*'
  - 'script/**/*'
  - 'spec/spec_helper.rb'
  - 'spec/cassettes/**/*'
  - 'features/**/*'
  - 'tmp/**/*'
  - 'vendor/**/*'
  - 'spec/models/word_document_spec.rb'
  - 'lib/cms/link_type/*.rb'
