development:
  adapter: mysql2
  username: root
  database: cms_development
  pool: 5
  timeout: 5000
  encoding: utf8

test:
  adapter: mysql2
  username: root
  database: cms_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  timeout: 5000
  encoding: utf8

# Do not keep production credentials in the repository,
# instead read the configuration from the environment.
#
# Example:
#   sqlite3://myuser:mypass@localhost/full/path/to/somedatabase
#
production:
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: true
  strict: false
  url: <%= ENV["MAS_FINCAP_CMS_DATABASE_URL"] %>


# We have this database configuration because we use the gem `js-routes` to allow us to access Rails routes from
# our JavaScript assets. Normally you configure the Rails application's `initialize_on_precompile` setting to false
# but `js-routes` requires an initialised Rails application so we include a database config for the `assets`
# environment to get Rails to initialize when we run `rake assets:precompile`.
assets:
  adapter: sqlite3
  database: db/assets.sqlite3
  pool: 5
  timeout: 5000
