#!/bin/bash -l

set -e

if [ -f /.dockerenv ]; then
    source ~/.bashrc
    rvm use default
    bundle config github.com $GITHUB_USER:$GITHUB_PASS
    mv config/database{-jenkins,}.yml
    mv .env{-example,}
fi

export RAILS_ENV=test
export BUNDLE_WITHOUT=development:build
export APP_NAME=MAS

exit_code=0

function run {
    declare -a tests_command=("$@")
    echo ''
    echo "=== Running \`${tests_command[*]}\`"
    if ! ${tests_command[*]}; then
        echo "=== These tests failed."
        exit_code=1
    fi
}

function info {
    declare -a info_command=("$@")
    echo ''
    echo "=== Running for informational purposes \`${info_command[*]}\`"
    if ! ${info_command[*]}; then
        echo "== This test has errors and/or warnings. Please review results"
    fi
}

run rm -rf vendor/cache .bundle/config
run bundle install --quiet
run npm install --quiet
run bundle exec bowndler update --allow-root
run bundle exec rake db:drop db:create db:schema:load db:migrate
run bundle exec rspec spec --format html --out tmp/spec.html --format RspecJunitFormatter --out tmp/spec.xml --format progress --profile --deprecation-out log/rspec_deprecations.txt
run bundle exec cucumber
run ./node_modules/karma/bin/karma start spec/javascripts/karma.conf.js --single-run
info brakeman -q --no-pager --ensure-latest
run bundle exec danger --dangerfile=jenkins/Dangerfile --verbose

exit "$exit_code"
